### ISSUE TITLE
UX: Dealing with options / parameters

### ISSUE THREAD

**Issue by otmarlendl** [ait-cs-IaaS/koord2ool#22]
Right now, there are two places where options are set:

1. on the top right, under the username. That settings page can change the timeslider setting
2. after the slides, "Display options"

The first "settings" doesn't really work for for me, as I can't easily move back to the survey. There is no "save", "exit" or similar UI Element. And the effects are a bit non-predictable. (it looks to me like it is using the index of the question as number of hours, not the value itself.

From a UX perspective, the Display options thingy works a lot better.

Recommendation: put all parameters we have in there. Incl. the timeslider settings and whatever else we might come up in the future. 

Maybe consider moving it up higher in the page, but this is optional.

**Comment by b3n4kh** [comment]
Solved in #27
