### ISSUE TITLE
Data Aggregation: Choose many questions

### ISSUE THREAD

**Issue by otmarlendl** [ait-cs-IaaS/koord2ool#26]
**Examples:**

* Please tick on this list which actions you performed:
* Who did you talk to?  [ ] Media, [ ] LE, [ ] CSIRT, [ ] Contractor

The aggregation is basically the same as for "[choose one](https://github.com/ait-cs-IaaS/koord2ool/issues/24)" questions. At the end, there is a count per answer for each relevant timestamp.

**Display:**

For the state display, a single ring/doughnut chart is not suitable. Something like [this](https://www.chartjs.org/docs/latest/samples/other-charts/multi-series-pie.html) (with thinner doughnuts and keeping a cutout in the middle) looks appropriate and has the same overall look.

For the time-series display, the same graph as for the "choose one" question can be used. The only difference is that stacking the lines does not make sense

**Comment by b3n4kh** [comment]
Aggregate similar to yes/no
