### ISSUE TITLE
Effect of "Time step" on the graph

### ISSUE THREAD

**Issue by otmarlendl** [ait-cs-IaaS/koord2ool#37]
(this is a feature request for the future, not a bug report)

Currently, the "Time Step" option only affects the timeslider on the top of the page.

It is worthwhile to explore how the "time step" could be used to influence the display of the timeline (chart on the right).

What about:

* change the option "Time display" from the binary "REAL" vs. "LOGICAL" to 
  - Realtime (answers are plotted at exactly the time they are received
  - Stepped (aggregate all answers within a time-step into one answer)
  - Logical (as initially planned)
* aggregation: 
 - I propose to use the state of the answers at the end of the given time interval
 - This might become configurable (max, min, avg, first, last ...)

**Comment by b3n4kh** [comment]
Add additional points at every "step" if in stepped mode
