### ISSUE TITLE
Don't round survey response dates

### ISSUE THREAD

**Issue by otmarlendl** [ait-cs-IaaS/koord2ool#5]
The graphs I get look like only the date part of the timestamp are used. 

I see no reason why the graphs shouldn't show the exact position where the value changes.

**Comment by MrManny** [comment]
https://github.com/ait-cs-IaaS/koord2ool/blob/main/src/components/surveys/LineChart.vue#L81 is the likely place to require the code change.

Otmar suggested a dropdown in the options that could influence this parameter.
